languageCode = "en-us"
baseURL = "//annappa.in/"
title = "Prof. Annappa B"
pagination.pagerSize = 5
theme = "PaperMod"

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

minify:
  disableXML = true
  minifyOutput = true

[params]
  env = "production"
  title = "Prof. Annappa B"
  description = "Experienced Professor, Former Head of the Department of Computer Science and Engineering and Chaimen CDC at National Institute of Technology Karnataka, Surathkal, INDIA..."
  keywords = ["Blog", "Portfolio", "Data Science"]
  DateFormat = "January 2, 2006"
  defaultTheme = "auto"
  disableThemeToggle = false
  social = [
    { name = "CV", url = "cv.pdf" },
    { name = "NITK Profile", url = "https://cse.nitk.ac.in/faculty/annappa" },
    { name = "googlescholar", url = "https://scholar.google.co.in/citations?user=X6XzPxYAAAAJ&hl=en" },
    { name = "linkedin", url = "https://www.linkedin.com/in/annappa/" },
    { name = "Email", url = "mailto:annappa@nitk.edu.in" },
    { name = "Scopus Profile", url = "https://www.scopus.com/authid/detail.uri?authorId=35179174200" }
  ]
  profileMode:
    enabled = true
    title = "Prof. Annappa B"
    subtitle = "**Professor** - Dept of CSE | **Chairman** - Career Development Center (CDC)"
    imageUrl = "picture.jpeg"
    imageWidth = 120
    imageHeight = 120
    imageTitle = "Annappa"
    buttons = [
      { name = "NITK", url = "https://www.nitk.ac.in/" },
      { name = "Sponserd Projects", url = "projects" },
      { name = "Invited Talks", url = "talks" },
      { name = "Awards", url = "awards" },
      { name = "Teaching", url = "teaching" }
    ]
  cover:
    hidden = true
    hiddenInList = true
    hiddenInSingle = false

menu:
  main:
    - identifier = "about"
      name = "About"
      url = "/about/"
      weight = 1
    - identifier = "service"
      name = "Service"
      url = "/service/"
      weight = 2
    - identifier = "publications"
      name = "Publications"
      url = "/publications/"
      weight = 3
    - identifier = "DISCOVER Lab @ NITK"
      name = "DISCOVER Lab @ NITK"
      url = "/lab/"
      weight = 4
    - identifier = "contact"
      name = "Contact"
      url = "/contact/"
      weight = 5
