languageCode: en-us
baseURL: "//chanin.tech/"
title: Prof. Annappa B
paginate: 5
theme: PaperMod

# assets:
#   - disableHLJS: true

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

#googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Prof. Annappa B
  description: "Experienced Professor, Former Head of the Department of Computer Science and Engineering and Chaimen CDC at **National Institute of Technology Karnataka**, Surathkal, INDIA with a demonstrated history of working in the higher education Institution. Well known Academician and Researcher in Computer Science & Engineering with Ph.D. and M.Tech. in Computer Science & Engineering from National Institute of Technology Karnataka and B.E. in Computer Science & Engineering, from Govt. B.D.T. College of Engineering Davangere, Karnataka. Working primarily in the areas of Cloud Computing, Data Science and Software Engineering."
  keywords: [Blog, Portfolio, Data Science]
  # author: Annappa
  # author: ["Me", "You"] # multiple authors
  #images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: false
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: false
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  label:
    text: "Prof. Annappa B"
    #icon: "images/coding.png"
    #iconHeight: 35

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: "Prof. Annappa B "
    subtitle: "**Professor** - Dept of CSE | **Chairman** - Career Development Center (CDC) | **President** - IIC, **National Institute of Technology Karnataka (NITK),** Surathkal, India."
    imageUrl: "picture.jpeg"
    imageWidth: 120
    imageHeight: 120
    imageTitle: "Annappa"
    buttons:
      - name: NITK
        url: "https://www.nitk.ac.in/"
      - name: Sponserd Projects
        url: projects
      - name: Invited Talks
        url: talks
      - name: Awards
        url: awards
      - name: Teaching
        url: teaching

  # home-info mode
  # homeInfoParams:
  #   Title: "Welcome! \U0001F44B"
  #   Content: ""

  socialIcons:
    - name: CV
      url: "cv.pdf"
    - name: NITK Profile
      url: "https://cse.nitk.ac.in/faculty/annappa"
    - name: googlescholar
      url: "https://scholar.google.co.in/citations?user=X6XzPxYAAAAJ&hl=en"
    - name: linkedin
      url: "https://www.linkedin.com/in/annappa/"
    - name: Email
      url: mailto:annappa@nitk.edu.in
    - name: Scopus Profile
      url: "https://www.scopus.com/authid/detail.uri?authorId=35179174200"

  ## google:
  #  SiteVerificationTag: "XYZabc"
  # bing:
  #  SiteVerificationTag: "XYZabc"
  #  yandex:
  #  SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: false # hide on single page

  editPost:
    #    URL: "https://github.com/chanin-www/content"
    #    Text: "Suggest Changes" # edit text
    URL: ""
    Text: "" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

  assets:
    favicon: "/favicon/favicon.ico"
    favicon16x16: "/favicon/favicon-16x16.png"
    favicon32x32: "/favicon/favicon-32x32.png"
    apple_touch_icon: "/favicon/apple-touch-icon.png"

menu:
  main:
    - identifier: about
      name: About
      url: /about/
      weight: 1
    - name: Service
      url: /service/
      weight: 2
    - identifier: Publications
      name: Publications
      url: /publications/
      weight: 3
    - identifier: DISCOVER Lab @ NITK
      name: DISCOVER Lab @ NITK
      url: /lab/
      weight: 4
    - identifier: Contact
      name: Contact
      url: /contact/
      weight: 5
    #- identifier: tags
    #  name: tags
    #  url: /tags/
    #  weight: 4

    #- identifier: example
    #  name: example.org
    #  url: https://example.org
    #  weight: 30
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
#     highlight:
#         anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         style: monokai

