languageCode: en-us
baseURL: "//annappa.in/"
title: Prof. Annappa B
pagination:
  pagerSize: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production  # to enable google analytics, opengraph, twitter-cards, and schema
  title: "Prof. Annappa B"
  description: "Experienced Professor, Former Head of the Department of Computer Science and Engineering and Chairman CDC at **National Institute of Technology Karnataka**, Surathkal, INDIA with a demonstrated history of working in higher education. Well-known Academician and Researcher in Computer Science & Engineering with a Ph.D. and M.Tech. in Computer Science & Engineering from NITK and B.E. in Computer Science & Engineering from Govt. B.D.T. College of Engineering, Davangere, Karnataka. Working primarily in the areas of Cloud Computing, Data Science, and Software Engineering."
  keywords:
    - Blog
    - Portfolio
    - Data Science
  DateFormat: "January 2, 2006"
  defaultTheme: auto  # dark, light
  disableThemeToggle: false
  ShowReadingTime: false
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: false
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  label:
    text: "Prof. Annappa B"
    # icon: "images/coding.png"
    # iconHeight: 35

  profileMode:
    enabled: true  # needs to be explicitly set
    title: "Prof. Annappa B "
    subtitle: "**Professor** - Dept of CSE | **Chairman** - Career Development Center (CDC) | **Chairman** - Centre for Cyber Physical Systems(CCPS), **National Institute of Technology Karnataka (NITK)**, Surathkal, India."
    imageUrl: "picture.jpeg"
    imageWidth: 120
    imageHeight: 120
    imageTitle: "Annappa"
    buttons:
      - name: "NITK"
        url: "https://www.nitk.ac.in/"
      - name: "Sponserd Projects"
        url: "projects"
      - name: "Invited Talks"
        url: "talks"
      - name: "Awards"
        url: "awards"
      - name: "Teaching"
        url: "teaching"

 [params]
  social = [
    { name = "CV", url = "cv.pdf" },
    { name = "NITK Profile", url = "https://cse.nitk.ac.in/faculty/annappa" },
    { name = "googlescholar", url = "https://scholar.google.co.in/citations?user=X6XzPxYAAAAJ&hl=en" },
    { name = "linkedin", url = "https://www.linkedin.com/in/annappa/" },
    { name = "Email", url = "mailto:annappa@nitk.edu.in" },
    { name = "Scopus Profile", url = "https://www.scopus.com/authid/detail.uri?authorId=35179174200" }
  ]


  cover:
    hidden: true  # hide everywhere but not in structured data
    hiddenInList: true  # hide on list pages and home
    hiddenInSingle: false  # hide on single page

  editPost:
    URL: ""
    Text: ""  # edit text
    appendFilePath: true  # to append file path to Edit link

  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys:
      - "title"
      - "permalink"
      - "summary"
      - "content"

assets:
  favicon: "/favicon/favicon.ico"
  favicon16x16: "/favicon/favicon-16x16.png"
  favicon32x32: "/favicon/favicon-32x32.png"
  apple_touch_icon: "/favicon/apple-touch-icon.png"

menu:
  main:
    - identifier: "about"
      name: "About"
      url: "/about/"
      weight: 1
    - name: "Service"
      url: "/service/"
      weight: 2
    - identifier: "publications"
      name: "Publications"
      url: "/publications/"
      weight: 3
    - identifier: "DISCOVER Lab @ NITK"
      name: "DISCOVER Lab @ NITK"
      url: "/lab/"
      weight: 4
    - identifier: "contact"
      name: "Contact"
      url: "/contact/"
      weight: 5
